// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function between(low, high, value) {
  if (Caml_obj.caml_lessequal(value, high)) {
    return Caml_obj.caml_greaterequal(value, low);
  } else {
    return false;
  }
}

function parseInput($$process, input) {
  return $$Array.map($$process, input.split("\n"));
}

function isEmptyList(list) {
  if (list) {
    return false;
  } else {
    return true;
  }
}

exports.between = between;
exports.parseInput = parseInput;
exports.isEmptyList = isEmptyList;
/* No side effect */
